name: tests function calculator

on: [push]

jobs:
    function-validation:
        runs-on: linux-latest

        steps:      
            - uses: actions/checkout@v4
            - name: Using Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18.
            - name: "Run install, build and test"
              run: |
                    npm install
                    npm run build
                    npm run test